import { GridIcon } from "@/icons";

const navItem = [
  {
    icon: <GridIcon />,
    name: "Dashboard",
    subItems: [
      {
        name: "Create Company",
        path: "/companies/create",
        requiredPermissions: "create:companies",
      },
      { name: "Analytics", path: "/companies/analytics" },
    ],
  },
];

const permissions = [
  "global:manage_companies",
  "create:companies",
  "view:companies",
  "update:companies",
  "delete:companies",
  "create:cash_sales",
  "view:cash_sales",
  "update:cash_sales",
  "delete:cash_sales",
  "create:sale_invoices",
  "view:sale_invoices",
  "update:sale_invoices",
  "delete:sale_invoices",
  "create:receipts",
  "view:receipts",
  "update:receipts",
  "delete:receipts",
  "create:delivery_orders",
  "view:delivery_orders",
  "update:delivery_orders",
  "delete:delivery_orders",
  "create:quotations",
  "view:quotations",
  "update:quotations",
  "delete:quotations",
  "create:proforma_invoices",
  "view:proforma_invoices",
  "update:proforma_invoices",
  "delete:proforma_invoices",
  "create:customer",
  "view:customer",
  "update:customer",
  "delete:customer",
  "create:credit_note",
  "view:credit_note",
  "update:credit_note",
  "delete:credit_note",
  "create:expenses_catagories",
  "view:expenses_catagories",
  "update:expenses_catagories",
  "delete:expenses_catagories",
  "create:purchase_invoices",
  "view:purchase_invoices",
  "update:purchase_invoices",
  "delete:purchase_invoices",
  "create:payment_vouchers",
  "view:payment_vouchers",
  "update:payment_vouchers",
  "delete:payment_vouchers",
  "create:goods_received",
  "view:goods_received",
  "update:goods_received",
  "delete:goods_received",
  "create:purchase_orders",
  "view:purchase_orders",
  "update:purchase_orders",
  "delete:purchase_orders",
  "create:suppliers",
  "view:suppliers",
  "update:suppliers",
  "delete:suppliers",
  "create:debit_note",
  "view:debit_note",
  "update:debit_note",
  "delete:debit_note",
];
