import { PERMISSIONS } from "./permissionMap";

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  admin: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_FINANCE,
    PERMISSIONS.CREATE_INVOICE,
    PERMISSIONS.VIEW_HR,
    PERMISSIONS.EDIT_HR,
    PERMISSIONS.VIEW_LOGISTIC,
    PERMISSIONS.MANAGE_USERS,
  ],
  finance: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_FINANCE,
    PERMISSIONS.CREATE_INVOICE,
  ],
  hr: [PERMISSIONS.VIEW_DASHBOARD, PERMISSIONS.VIEW_HR, PERMISSIONS.EDIT_HR],
  logistic: [PERMISSIONS.VIEW_DASHBOARD, PERMISSIONS.VIEW_LOGISTIC],
  shareholder: [PERMISSIONS.VIEW_DASHBOARD, PERMISSIONS.VIEW_SHAREHOLDER],
  superadmin: Object.values(PERMISSIONS),
};
